// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDotz-5JjllRf_jppgowzRjT7ADr5WrV3k',
    appId: '1:487217403446:web:dfc974af7d662421616a97',
    messagingSenderId: '487217403446',
    projectId: 'navcare-f864c',
    authDomain: 'navcare-f864c.firebaseapp.com',
    storageBucket: 'navcare-f864c.firebasestorage.app',
    measurementId: 'G-DW0JT9LB46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfJbqRr3ZI0PmvOU-5HAUWWXRMLxJk0aU',
    appId: '1:487217403446:android:585268be69461480616a97',
    messagingSenderId: '487217403446',
    projectId: 'navcare-f864c',
    storageBucket: 'navcare-f864c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO__2AyonnhYgTHek0cy-gZ-4rh8E-ckk',
    appId: '1:487217403446:ios:54a5398858e8f1bd616a97',
    messagingSenderId: '487217403446',
    projectId: 'navcare-f864c',
    storageBucket: 'navcare-f864c.firebasestorage.app',
    iosClientId: '487217403446-dgab31hffefa4125rarkohjhm0dula21.apps.googleusercontent.com',
    iosBundleId: 'com.example.navCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO__2AyonnhYgTHek0cy-gZ-4rh8E-ckk',
    appId: '1:487217403446:ios:54a5398858e8f1bd616a97',
    messagingSenderId: '487217403446',
    projectId: 'navcare-f864c',
    storageBucket: 'navcare-f864c.firebasestorage.app',
    iosClientId: '487217403446-dgab31hffefa4125rarkohjhm0dula21.apps.googleusercontent.com',
    iosBundleId: 'com.example.navCareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDotz-5JjllRf_jppgowzRjT7ADr5WrV3k',
    appId: '1:487217403446:web:a68ea1ec57af0aee616a97',
    messagingSenderId: '487217403446',
    projectId: 'navcare-f864c',
    authDomain: 'navcare-f864c.firebaseapp.com',
    storageBucket: 'navcare-f864c.firebasestorage.app',
    measurementId: 'G-K1MW4QMGJP',
  );

}